version: '3'
services:
  web:
    build:
      context: .
      dockerfile: etc/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql

  cli:
    build:
      context: .
      dockerfile: etc/Dockerfile.cli
    volumes:
      - ./app:/app
    command: "php create_tbl.php"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test-password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
