apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx1
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: custom-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: custom-html
        configMap:
          name: nginx-configmap1
