apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap2
data:
  index.html: |
    <html lang="en">
    <head><title>Welcome to Nginx 2!</title></head>
      <body>
        <h1>Hello from Nginx Deployment 2!</h1>
      </body>
    </html>
